(async function () {
  const state = { password: "", data: null };
  const login = document.getElementById("login"); const dashboard = document.getElementById("dashboard"); const status = document.getElementById("save-state");
  document.getElementById("login-form").onsubmit = async (event) => { event.preventDefault(); state.password = document.getElementById("password").value; const response = await fetch("/api/content"); if (!response.ok) { document.getElementById("login-status").textContent = "Studio is not reachable."; return; } state.data = await response.json(); login.hidden = true; dashboard.hidden = false; render(); };
  document.getElementById("logout").onclick = () => location.reload();
  const field = (label, key, value, rows = 2) => `<label>${label}<textarea data-key="${key}" rows="${rows}">${value || ""}</textarea></label>`;
  function render() {
    const data = state.data;
    [["hero-title", data.hero.title], ["hero-intro", data.hero.intro], ["about-title", data.about.title], ["about-lead", data.about.lead], ["about-copy", data.about.copy], ["journey-title", data.journey.title], ["journey-intro", data.journey.intro], ["contact", data.settings.contact], ["linkedin", data.settings.linkedin], ["github", data.settings.github], ["whatsapp", data.settings.whatsapp], ["hero-image", data.settings.heroImage]].forEach(([name, value]) => { const element = document.querySelector(`[name="${name}"]`); if (element) element.value = value || ""; });
    Object.entries(data.settings.visible).forEach(([key, value]) => { document.querySelector(`[data-visible="${key}"]`).checked = value; });
    document.getElementById("project-editors").innerHTML = data.projects.map((item, index) => `<div class="editor-card"><div class="editor-card-header"><strong>Project ${String(index + 1).padStart(2, "0")}</strong></div>${field("Project name (HTML allowed)", `project-${index}-title`, item.title)}${field("Category", `project-${index}-type`, item.type)}${field("Description", `project-${index}-text`, item.text, 3)}${field("Technology tags, separated by commas", `project-${index}-tags`, item.tags.join(", "))}</div>`).join("");
    document.getElementById("journey-editors").innerHTML = data.journey.items.map((item, index) => `<div class="editor-card"><div class="editor-card-header"><strong>Chapter ${String(index + 1).padStart(2, "0")}</strong><button type="button" class="remove-button" data-remove="${index}">Remove</button></div>${field("Date", `journey-${index}-date`, item.date)}${field("Title", `journey-${index}-title`, item.title)}${field("Description", `journey-${index}-text`, item.text, 3)}<label><input type="checkbox" data-current="${index}" ${item.current ? "checked" : ""}> Current chapter</label></div>`).join("");
    document.querySelectorAll("[data-remove]").forEach((button) => button.onclick = () => { data.journey.items.splice(Number(button.dataset.remove), 1); render(); });
    document.getElementById("archive-editors").innerHTML = data.archive.length ? data.archive.map((item, index) => `<div class="archive-row"><span><strong>${item.title}</strong><small>${item.kind || "Archive"} · ${item.filename || ""}</small></span><button type="button" class="remove-button" data-delete="${index}">Remove</button></div>`).join("") : '<p class="section-label">No archive items yet.</p>';
    document.querySelectorAll("[data-delete]").forEach((button) => button.onclick = () => { data.archive.splice(Number(button.dataset.delete), 1); render(); });
  }
  function collect() {
    const data = state.data; const get = (name) => document.querySelector(`[name="${name}"]`).value;
    data.hero.title = get("hero-title"); data.hero.intro = get("hero-intro"); data.about.title = get("about-title"); data.about.lead = get("about-lead"); data.about.copy = get("about-copy"); data.journey.title = get("journey-title"); data.journey.intro = get("journey-intro"); data.settings.contact = get("contact"); data.settings.linkedin = get("linkedin"); data.settings.github = get("github"); data.settings.whatsapp = get("whatsapp"); data.settings.heroImage = get("hero-image");
    Object.keys(data.settings.visible).forEach((key) => { data.settings.visible[key] = document.querySelector(`[data-visible="${key}"]`).checked; });
    data.projects = data.projects.map((item, index) => ({ title: document.querySelector(`[data-key="project-${index}-title"]`).value, type: document.querySelector(`[data-key="project-${index}-type"]`).value, text: document.querySelector(`[data-key="project-${index}-text"]`).value, tags: document.querySelector(`[data-key="project-${index}-tags"]`).value.split(",").map((tag) => tag.trim()).filter(Boolean) }));
    data.journey.items = data.journey.items.map((item, index) => ({ date: document.querySelector(`[data-key="journey-${index}-date"]`).value, title: document.querySelector(`[data-key="journey-${index}-title"]`).value, text: document.querySelector(`[data-key="journey-${index}-text"]`).value, current: document.querySelector(`[data-current="${index}"]`).checked }));
    return data;
  }
  document.getElementById("add-journey").onclick = () => { state.data.journey.items.push({ date: "NEW", title: "New chapter", text: "Describe this chapter." }); render(); };
  document.getElementById("file").onchange = (event) => { document.getElementById("file-label").textContent = event.target.files[0] ? event.target.files[0].name : "Choose image, PDF, video, or any file"; };
  document.getElementById("add-file").onclick = () => { const file = document.getElementById("file").files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { state.data.archive.unshift({ title: document.getElementById("file-title").value || file.name, description: document.getElementById("file-description").value, kind: file.type.startsWith("image/") ? "Photo" : "File", filename: file.name, image: file.type.startsWith("image/") ? reader.result : "", file: reader.result }); render(); }; reader.readAsDataURL(file); };
  document.getElementById("content-form").onsubmit = async (event) => { event.preventDefault(); status.textContent = "Publishing…"; const response = await fetch("/api/content", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password: state.password, content: collect() }) }); const result = await response.json(); status.textContent = response.ok ? "Published globally ✓" : (result.error || "Publish failed."); status.className = response.ok ? "save-state status-good" : "save-state status-bad"; };
})();
